### ISSUE TITLE
Support for new CheckMK versions

### ISSUE THREAD

**Issue by irfannaseefp** [FlorianHeigl/nagios#2]
Getting following error with CheckMK raw edition 1.6.0p11. Please update the plugin for the newer versions.

> UNKN - The discovery function "inventory_xen_mem" of the check "xen.mem" is expected to take a single argument (info or parsed), but it's taking the following arguments: ['checkname', 'info']. You will have to change the arguments of the discovery function to make it compatible with this Checkmk version.

**Comment by FlorianHeigl** [comment]
Hi,

I wasn't able to work on this for the whole year so far.
Plus, I don't got a running Xen host at the moment.

I'm aiming to re-package all the Check_MK plugins & CI build them (did this for customers, so it's just replicating).
At the latest for this I'll be able to fix your bug.

Would you mind if it'll be a release straight for Check_MK 2.0?

**Comment by irfannaseefp** [comment]
Thank you.  I have upgraded my environment to 2.0.0 . Also, i have done little changes to the Xen plugin as per the documentation for writing plugins, and it is working for me ( [https://github.com/irfannaseefp/checkmk_plugins/blob/main/xen_vms.py](https://github.com/irfannaseefp/checkmk_plugins/blob/main/xen_vms.py) ).

**Comment by FlorianHeigl** [comment]
Hey, thanks for the update. 
I've pulled in your code and linked to it - I had thought I had already done this...
In any case, no point in keeping around a dated version. I can remember I was building a CI for upgrading all checks but this will not finish any time soon :-(

Wishing you a nice new year, and xmas, if applicable.

(If anyone still needs the 1.x version they can always find it in the history)
